server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cdb-3d9ehih5.sql.tencentcdb.com:26921/underware
    username: onebox
    password: 9TXMan.!g9jfv7K
    # url: jdbc:mysql://localhost:3306/onebox
    # username: root
    # password: 12345678
  mvc:
    view:
      suffix: .html
      prefix: /
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "高我接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.tencent.wxcloudrun.controller
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
langchain4j:
  open-ai:
    chat-model:
      model-name: deepseek-chat
      base-url: https://api.deepseek.com/v1
      api-key: sk-092cc51ff94f4d6db9302386a14962ac
      log-requests: true
      log-responses: true
wx:
  miniapp:
    appid: wx2584d463c0bb7200
    secret: 4f07200792becd8348ed877f59b9c2b2